### ISSUE TITLE
Check how we can migrate from GitBook to Git (or other solution)

### ISSUE THREAD

**Issue by kaiquemancoso** [Flutter-Vision/FluterVision#106]
We are paying more than 50 euros per month on GitBook, to have the documentation and product changelog. We need to migrate from GitBook for a free solution, maybe with a repository on Git. Any questions, ask Bruno.

**Comment by pattrickx** [comment]
we can use GITHUB WIKI or GitHub Pages, on GitHub Pages we can do something more customizable since it basically works like a WEB page @kaiquemancoso @brunoamuniz @WixeI

**Comment by ZoiParaschou** [comment]
I found this link which proposes some alternatives too. https://freestuff.dev/alternative/gitbook/

**Comment by teras** [comment]
Closing sue to move to GItLab
