### ISSUE TITLE
Modal to ask Discord and Telegram for users 

### ISSUE THREAD

**Issue by kaiquemancoso** [Flutter-Vision/FluterVision#108]
A modal at the first user access, with a form:
Can we contact you to ask feedback?
Tell us how can we talk.
Telegram:
Discord

For Ricardo : Add field on user "discord" and "telegram"

**Comment by ricardobna** [comment]
Added a field to the User called "firstUsage" to know if this modal should be presented.

**Comment by ricardobna** [comment]
Branch for this issue is fix/#108.
