### ISSUE TITLE
Login with Google are getting only Email, not the User Name, on the Log File

### ISSUE THREAD

**Issue by kaiquemancoso** [Flutter-Vision/FluterVision#114]
It seems we are getting Email twice, instead of collecting the User Name,  when the subscription is done via Google account. On User Log, we have the same information on Name and Email. 

<img width="769" alt="Screen Shot 2022-04-14 at 10 21 27" src="https://user-images.githubusercontent.com/71526720/163399713-66561c8e-26b6-4836-8663-c5bfeebf2a1a.png">

Question: Can we collect the User Name from Google? 

Also when we don't have the user name, the Field Name should be NA. 

Thanks!

**Comment by dkatsianos** [comment]
@kaiquemancoso about this, when we login with google account the email and username is the same. So, thaths you have twice the email

**Comment by dkatsianos** [comment]
@kaiquemancoso maybe this has been resolved it by Paulo. The code seems right.
