### ISSUE TITLE
Bug when you insert a invalid username/passowrd

### ISSUE THREAD

**Issue by rene-kt** [Flutter-Vision/FluterVision#115]

**Comment by rene-kt** [comment]
![image](https://user-images.githubusercontent.com/49681380/163423957-a6aa6eb2-81be-4715-9718-1da92570dd28.png)

what happens: 

![image](https://user-images.githubusercontent.com/49681380/163424077-e9d2e4d0-2044-41eb-b963-3319b4063eb8.png)

**Comment by dkatsianos** [comment]
About this issue guys, I think resolved with the issue https://github.com/Flutter-Vision/FlutterVision/issues/120.
So dont spend any other time.
