### ISSUE TITLE
Background image on export

### ISSUE THREAD

**Issue by mateuslimax22** [Flutter-Vision/FluterVision#123]
![image](https://user-images.githubusercontent.com/38704964/164015682-e04fc870-6221-497f-9eb9-3c7b01a61e9e.png)

![image](https://user-images.githubusercontent.com/38704964/164015790-a9a15a62-dbd6-4ee7-8fec-1e39bca12915.png)
how should be.
ex:
![image](https://user-images.githubusercontent.com/38704964/164016015-b0d2ca5d-cfc5-4433-89ca-0d996207a8e1.png)

**Comment by reness0** [comment]
duplicated #35
