### ISSUE TITLE
Put shadows on components

### ISSUE THREAD

**Issue by mateuslimax22** [Flutter-Vision/FluterVision#129]
![image](https://user-images.githubusercontent.com/38704964/164024701-01c8c0a0-97f5-4d7d-a48c-43b76e9057a0.png)

![image](https://user-images.githubusercontent.com/38704964/164045035-8c59dea8-c4c6-4579-9e94-6310ed8bcb41.png)

**Comment by pattrickx** [comment]
Shadow json sample


```json
"style":{
          "shadow":{
                          "type": "drop_shadow",
                          "color": "#000000",
                          "transparency": 0.15999999642372131
                          "blendMode": "normal",
                          "offset": {
                              "x": 0.0,
                              "y": 4.0
                          },
                          "radius": 8.0,
                          "showShadowBehindNode": true
                      }
}
```

**Comment by brunoamuniz** [comment]
I tested but could not see the shadow in the front end nor in the flutter exported

using the same example in the issue to test

**Comment by brunoamuniz** [comment]
I can see the shadow on the front end but it is not applying to this button in the image, in the Flutter code

SECONCI example used to test

<img width="737" alt="Screen Shot 2022-05-06 at 13 31 50" src="https://user-images.githubusercontent.com/3296036/167174640-18ebe541-4c2c-43f7-b49d-03a6c4cdee5e.png">
