### ISSUE TITLE
Rontend getting json info from backend but not exiting load screen

### ISSUE THREAD

**Issue by pattrickx** [Flutter-Vision/FluterVision#130]
Backtest test when running a figma project the frontend is getting stuck on load, the AI ​​and backend result was checked and they are ok.
![image](https://user-images.githubusercontent.com/32752004/164058942-eda6c017-a61d-40d0-b1a3-d7048f826731.png)

**Comment by dkatsianos** [comment]
I think the bug was created from my last changes. I will resolved today @pattrickx. It is my fault.

**Comment by dkatsianos** [comment]
@pattrickx i need to change the axios timeout. 60000 ms is it enough for the prediction time ?
