### ISSUE TITLE
Raise the confidence threshold for AI

### ISSUE THREAD

**Issue by pattrickx** [Flutter-Vision/FluterVision#131]
Could be a way to limit AI misdetections

**Comment by brunoamuniz** [comment]
This component is clearly a button and the AI is not detecting anymore.

Do you think there is  anything we can do about it??

<img width="210" alt="Screen Shot 2022-04-22 at 10 20 53" src="https://user-images.githubusercontent.com/3296036/164722494-a050895b-0cfc-46f0-a444-c66a271e9e5a.png">

**Comment by brunoamuniz** [comment]
just an observation

our competitor is doing some kind of grouping in the components even if the designer didnt make it in the figma file... Take a look

![Screen Shot 2022-04-22 at 10 23 20](https://user-images.githubusercontent.com/3296036/164723257-9a879036-85dc-46b2-9eeb-5a555c27cc46.png)

<img width="341" alt="Screen Shot 2022-04-22 at 10 23 47" src="https://user-images.githubusercontent.com/3296036/164723280-2402183b-d539-46b3-9b95-14ddf7f7ff0e.png">


This is impacting directly in the export
