### ISSUE TITLE
#197 Some background colors are different from the expected

### ISSUE THREAD

**Issue by rene-kt** [Flutter-Vision/FluterVision#133]

**Comment by rene-kt** [comment]
![image](https://user-images.githubusercontent.com/49681380/164229839-c9c9523a-a756-4123-8319-4cf9e1f0e8d8.png)

![image](https://user-images.githubusercontent.com/49681380/164229943-b9c0f600-0a79-479c-a163-aacf3b866bf0.png)

![image](https://user-images.githubusercontent.com/49681380/164230021-37b815a0-67f4-439e-a61d-ffd0a1c02fc0.png)

![image](https://user-images.githubusercontent.com/49681380/164230116-7952ed7a-6ada-40b2-9e13-739f9b6add8e.png)

**Comment by pattrickx** [comment]
All colors in the fix/#133 branch are being shipped as RGBA, as in the following images.
@reness0 @mateuslimax22 
![image](https://user-images.githubusercontent.com/32752004/165556195-dcc3f882-3de3-4bcf-a223-0fddf9f34dc7.png)
![image](https://user-images.githubusercontent.com/32752004/165556254-9dca4e8a-008e-4ea4-82b2-8a8c4014936c.png)
