### ISSUE TITLE
figma component with width 0 is breaking the backend and stoping the import

### ISSUE THREAD

**Issue by brunoamuniz** [Flutter-Vision/FluterVision#145]
hello guys,

we are having a blocker issue with components with 0 width or/and height.

No information is shown to the user, only an error.. We should let it pass in the backend, this is probably a mistake from the designer.

if you want to try it, prototype number 8 in the list.

![photo_2022-04-25_14-45-21](https://user-images.githubusercontent.com/3296036/165144685-772dcfec-e7dd-45c8-8651-53ae7ef4a8bc.jpg)
![photo_2022-04-25_14-45-30](https://user-images.githubusercontent.com/3296036/165144690-3540661c-37a0-4881-bdae-452e9db3dbef.jpg)

**Comment by ricardobna** [comment]
Branch for this issue is fix/#145
