### ISSUE TITLE
Switch components using tileColor property

### ISSUE THREAD

**Issue by ricardobna** [Flutter-Vision/FluterVision#146]
I  created a switch from scratch on the fluttervision webpage and after exporting it came with a `tileColor` property to it, the only `tileColor` reference I could find while searching for it was on [SwitchListTile](https://api.flutter.dev/flutter/material/SwitchListTile/tileColor.html).

![image](https://user-images.githubusercontent.com/26353566/165301622-fc7081ec-59b1-4003-adb8-c8147b15625c.png)

**Comment by ZoiParaschou** [comment]
is fixed
