### ISSUE TITLE
Some images files are not coming (speacially when they are vectors inside figma) 

### ISSUE THREAD

**Issue by rene-kt** [Flutter-Vision/FluterVision#148]
![image](https://user-images.githubusercontent.com/49681380/165306025-9a6b77e4-f50c-46fa-837f-b77bdf2ae8fd.png)

![image](https://user-images.githubusercontent.com/49681380/165306090-04c6c3b3-6974-4fd0-a355-cd1d13846179.png)

https://www.figma.com/file/IwF6KAqUJieRMqkxO5nu1g/Seconci-Sample-5-screens-(Copy)?node-id=82%3A1055

**Comment by pattrickx** [comment]
figma is returning null for the quest value of some images
