### ISSUE TITLE
Refactor the export templates code

### ISSUE THREAD

**Issue by pedrohcbrl** [Flutter-Vision/FluterVision#152]
The following components must be on separated template files.

### Components

- [x] Container @reness0 @pedrohcbrl 
- [x] TextView @pedrohcbrl 
- [x] Button @ricardobna 
- [x] EditText @reness0  
- [x] ImageView @pedrohcbrl  
- [x] ImageButton @ricardobna  
- [x] CheckBox @reness0 
- [x] RadioButton @pedrohcbrl 
- [x] Switch @ricardobna  
- [x] Spinner @reness0  
- [x] ProgressBar @pedrohcbrl  
- [x] Slider @ricardobna

**Comment by pedrohcbrl** [comment]
Absolute Layout doesn't export sometimes and Relative Layout needs reorder components based on X axis before export.

**Comment by kaiquemancoso** [comment]
I tried this sample: [https://www.figma.com/file/1ssfUSDciipd9tiXDwGePe/Components?node-id=0%3A1](https://www.figma.com/file/1ssfUSDciipd9tiXDwGePe/Components?node-id=0%3A1) but I couldn't export. I put all kind of components on the screen and got this error: The export has failed. Please contact with administrator.
