### ISSUE TITLE
Radio button not working 

### ISSUE THREAD

**Issue by brunoamuniz** [Flutter-Vision/FluterVision#153]
Radio button is break the flutter code

I am using this application and it is need to change the type in the front end

https://www.figma.com/file/Q7Fh2cEbTEZIoSaR6bbaIY/Sign-Up%2FLogin-Form-(Community)?node-id=1%3A76

error

<img width="490" alt="Screen Shot 2022-04-27 at 11 02 35" src="https://user-images.githubusercontent.com/3296036/165536814-a5315eaf-2390-4e1e-9a81-ca5799f810ff.png">

**Comment by pedrohcbrl** [comment]
Solution included on issue #154 , it was the same problem.
