### ISSUE TITLE
Update the Privacy Policy to include figma permissions

### ISSUE THREAD

**Issue by WixeI** [Flutter-Vision/FluterVision#155]
We are using markdown style to present the Private Policy. That allows the correct team to make changes in the file if necessary (without the need of programming knowledge)

Privacy Policy markdown file to edit:
[privacy-policy.md](https://github.com/Flutter-Vision/FlutterVision/files/8578255/privacy-policy.md)

Edit, post it here in the comments or send it to me, then I'll update the front-end with the new file

PS: I sugest you use a markdown editor to see the results. The one I'm using is "https://stackedit.io/", but feel free to do as you see fit

**Comment by brunoamuniz** [comment]
@WixeI here it comes!! 

[privacy-policy.md](https://github.com/Flutter-Vision/FlutterVision/files/8585544/privacy-policy.md)
