### ISSUE TITLE
Spinner being exported with error after creating it on webpage

### ISSUE THREAD

**Issue by ricardobna** [Flutter-Vision/FluterVision#161]
I created a Spinner using the tool on the webpage and after exporting the project I get the following with errors:
![image](https://user-images.githubusercontent.com/26353566/165965573-c2efe97d-8563-473c-ba63-dde9b074e936.png)
This is how the component is on the tool:
![image](https://user-images.githubusercontent.com/26353566/165965687-bf4f8198-3f74-4efe-826b-ec87381433bc.png)
Lastly, to solve this issue I added the following variables to the `_Framescreen1State` class:
![image](https://user-images.githubusercontent.com/26353566/165965836-bad7cff8-f60b-4352-9f0e-cfa9e3224c28.png)
And removed the `const` from DropdownButton
![image](https://user-images.githubusercontent.com/26353566/165965967-ded22e20-7dcc-4793-85af-611a19c18214.png)

**Comment by ZoiParaschou** [comment]
This is fixed
