### ISSUE TITLE
not getting the right background color from Figma

### ISSUE THREAD

**Issue by brunoamuniz** [Flutter-Vision/FluterVision#167]
FV is not getting the right background color from figma

example number 3 from spreadsheet

<img width="586" alt="Screen Shot 2022-05-03 at 11 15 34" src="https://user-images.githubusercontent.com/3296036/166471020-ed31df33-abba-475d-9499-3cb513154141.png">

<img width="416" alt="Screen Shot 2022-05-03 at 11 15 53" src="https://user-images.githubusercontent.com/3296036/166471054-523607df-5469-45d9-8f1d-1ede51f82498.png">

**Comment by pattrickx** [comment]
this is already being done in the issue #133
