### ISSUE TITLE
Backend error: I cannot export projects

### ISSUE THREAD

**Issue by brunoamuniz** [Flutter-Vision/FluterVision#188]
Backend error: I cannot export projects

example used: https://www.figma.com/file/UmW0w5pg8aYufDKaHQidxM/KCBank-(Copy)?node-id=0%3A1

trying on https://backtest.fluttervision.com/

![photo_2022-05-05_11-23-14](https://user-images.githubusercontent.com/3296036/166949980-fcce7069-8464-4ac9-b862-7b93f8ec4253.jpg)
<img width="454" alt="Screen Shot 2022-05-05 at 11 12 00" src="https://user-images.githubusercontent.com/3296036/166949991-7a5004a1-180c-43a7-af01-f182f7c26ae7.png">

**Comment by teras** [comment]
the flutter template breaks around hug properties... maybe it's random.

@dkatsianos why we don't have the exception id number and we just have a description?

**Comment by dkatsianos** [comment]
> the flutter template breaks around hug properties... maybe it's random.
> 
> @dkatsianos why we don't have the exception id number and we just have a description?

@teras its seems that we didn't catch the error on backend or backend didn't send error status code on its response. This message, have created from frontend, for this reason we didnt have exception id number.
