### ISSUE TITLE
Bug: white screen of death in the front end when change the type or delete components 

### ISSUE THREAD

**Issue by brunoamuniz** [Flutter-Vision/FluterVision#193]
I am trying to test the issues but I am having an error when I try to change the type of components or when I try to delete one too.

the system breaks and I cannot do anything else...

<img width="536" alt="Screen Shot 2022-05-06 at 13 54 04" src="https://user-images.githubusercontent.com/3296036/167179095-2b9433fd-e633-4fbc-ab7b-dcd97caded46.png">

**Comment by dkatsianos** [comment]
related with -> https://github.com/Flutter-Vision/FlutterVision/issues/196 and https://github.com/Flutter-Vision/FlutterVision/issues/195
