### ISSUE TITLE
Front didn't update image background image

### ISSUE THREAD

**Issue by brunoamuniz** [Flutter-Vision/FluterVision#197]
I changed the image background using FV web but it didnt change in the generated Flutter code

<img width="535" alt="Screen Shot 2022-05-09 at 10 55 27" src="https://user-images.githubusercontent.com/3296036/167425818-646e3314-13e9-44cb-8cba-7e371a460d8f.png">

**Comment by WixeI** [comment]
Send me the link of the project you tested on if you can, please

**Comment by brunoamuniz** [comment]
item 65 of our spreadsheet, bank app design

**Comment by brunoamuniz** [comment]
not happening anymore!!
