### ISSUE TITLE
#244 Changing Types of components in FV not working for some components

### ISSUE THREAD

**Issue by brunoamuniz** [Flutter-Vision/FluterVision#198]
When you change the type of some components, we cannot save the screen anymore and an error is showing to us

the components with problems are:

Inkwell
Image
Linerprogressbox
seekbar

<img width="552" alt="Screen Shot 2022-05-09 at 15 46 23" src="https://user-images.githubusercontent.com/3296036/167476763-c11706ea-6915-4489-b34b-7c536d0bb13c.png">

**Comment by kaiquemancoso** [comment]
I tested trying to change the mentioned components and FV failed with Image, Linerprogressbox e seekbar.

**Comment by kaiquemancoso** [comment]
Using this sample: https://www.figma.com/file/hhIGxM7o6Svm9o0rnV5SKz/KnowCommerce?node-id=115%3A3103
On the first page, try to create a container and convert it into Linerprogressbox e seekbar.
On the third page, select the Arrow and try to convert it into Image.

**Comment by WixeI** [comment]
Update: the bug occurs only when the screen is in Stack layout. With Relative Layout screens it works fine. Will keep working to fix it.
