### ISSUE TITLE
back is changing the size of images

### ISSUE THREAD

**Issue by brunoamuniz** [Flutter-Vision/FluterVision#199]
back is changing the size of images and when I run on Flutter it is breaking the format of the application

original image

![image](https://user-images.githubusercontent.com/3296036/167630105-55757632-b035-4c2e-a7c2-23d3359b8c7c.png)

after processing in FV

![image_ImageView_20-73x686](https://user-images.githubusercontent.com/3296036/167630171-7cedd841-3a5a-4fe0-b8f9-f4211892a590.png)

[Project.zip](https://github.com/Flutter-Vision/FlutterVision/files/8661524/Project.zip)

**Comment by ricardobna** [comment]
Tried this on latest development branch and the images are fine as you can see: [assets.zip](https://github.com/Flutter-Vision/FlutterVision/files/8670813/assets.zip)

**Comment by ricardobna** [comment]
Tested with @brunoamuniz and this appears to be related to a local issue on his computer, when he changed browsers the bug seemed to be gone. 
Browser: Google Chrome 101.0.4951.64
OS: MacOS Montrey 12.3.1
