### ISSUE TITLE
#191 Refactor deep text

### ISSUE THREAD

**Issue by pattrickx** [Flutter-Vision/FluterVision#201]
To test, verify that the texts of the components that accept text are the same as those of figma

**Comment by kaiquemancoso** [comment]
I tested this sample: [https://www.figma.com/file/hhIGxM7o6Svm9o0rnV5SKz/KnowCommerce?node-id=115%3A3107](https://www.figma.com/file/hhIGxM7o6Svm9o0rnV5SKz/KnowCommerce?node-id=115%3A3107)

On the second screen, the button REGISTRAR has no label.
