### ISSUE TITLE
#191 Restructure figma data processing class

### ISSUE THREAD

**Issue by pattrickx** [Flutter-Vision/FluterVision#206]
# How to test

For this issue I need a general test of the properties of the components, and a report of what is not coming from figma to our frontend.

Whoever is going to test needs to check if the information defined in figma is being displayed on the frontend.

Properties to be verified:
- [x]  Width
- [x] Height
- [x] Corner Radius
- [x] Stroke Weight
- [x] StrokeAlign
- [x] Background Color
- [x] Shadow
- [x] Text
- [x] Font Color
- [x] Font Weight
- [x] Font Family
- [x] Font Size
- [x] Check if the exported image is the one that should be in the component
- [x] Layout

**Comment by pattrickx** [comment]
for this issue I need a general test of the properties of the components, and a report of what is not coming from figma to our frontend.

whoever is going to test needs to check if the information defined in figma is being displayed on the frontend.

Properties to be verified:
- [ ]  Width
- [ ] Height
- [ ] Corner Radius
- [ ] Stroke Weight
- [ ] StrokeAlign
- [ ] Background Color
- [ ] Shadow
- [ ] Text
- [ ] Font Color
- [ ] Font Weight
- [ ] Font Family
- [ ] Font Size
- [ ] Image Name
- [ ] Layout

**Comment by kaiquemancoso** [comment]
Guys, what is Font Weight? I'm not finding it on Figma. @pattrickx @WixeI

**Comment by kaiquemancoso** [comment]
Image Name is different on frontend. Example: 
On Figma: notifications_white_24dp 1
On FlutterVision: notificationswhitedp_ImageView_9
On Export: notificationswhitedp_ImageView_9-24x24
Sample: https://www.figma.com/file/Sx7HqLk6EAQDBwnUhGlKqL/KCBank?node-id=1%3A2

**Comment by pattrickx** [comment]
I changed the item about image name, I think it makes more sense now @kaiquemancoso
