### ISSUE TITLE
User log disappeared from admin profile =(

### ISSUE THREAD

**Issue by brunoamuniz** [Flutter-Vision/FluterVision#222]
we cannot access the user log anymore, when we log in with admin account

<img width="563" alt="Screen Shot 2022-05-13 at 08 22 58" src="https://user-images.githubusercontent.com/3296036/168273394-59bad136-985d-4475-8e94-4a410ef4c7e3.png">

**Comment by dkatsianos** [comment]
I have added logout button for admin also, and I resolve the problem for admin account.
