### ISSUE TITLE
#213 Changing type of component is missplacing it on the top of the project

### ISSUE THREAD

**Issue by WixeI** [Flutter-Vision/FluterVision#227]
If you change the type of a component and it stays in the same place, that means the bug is fixed.

**Comment by kaiquemancoso** [comment]
I tested with this sample: https://www.figma.com/file/Sx7HqLk6EAQDBwnUhGlKqL/KCBank?node-id=0%3A1
On the screen 2 I changed the TextField to Container and it moved.
