### ISSUE TITLE
#158 Receive the group component information and pass it to the template correctly (Receive the components as StackLayout and convert it to Row and Columns)

### ISSUE THREAD

**Issue by rene-kt** [Flutter-Vision/FluterVision#229]
This issue is related to that one -> https://github.com/Flutter-Vision/FlutterVision/issues/158

How to test it: 

Check if in the flutter application, the container that you grouped (#158) are behaving like a row in the export

**Comment by kaiquemancoso** [comment]
Waiting for more explanation from @reness0

**Comment by kaiquemancoso** [comment]
Figma file to test: https://www.figma.com/file/1KqEMutQUOFq1nUotxvAys/Job-Finding-app-Community-Copy-Copy

**Comment by kaiquemancoso** [comment]
DECLINED: When grouping the first 3 components, the container is small then it should be.

<img width="930" alt="Screen Shot 2022-05-24 at 15 59 59" src="https://user-images.githubusercontent.com/71526720/170341440-928a4076-d855-4f02-89d6-b9f2b760ef35.png">
