### ISSUE TITLE
Implement "backgroundColor" property processing

### ISSUE THREAD

**Issue by WixeI** [Flutter-Vision/FluterVision#230]
Process how to pass information from " backgroundColor" properties of children of a container to a component that changed type and supports "backgroundColor"

PS: By the end of this task, the parentContainer, when changed, will get the backgroundColor based on the last child of its list of children. A different and more accurate way of processing will be done in issue #231

**Comment by kaiquemancoso** [comment]
I'm still having problems when changing the component type. Sometimes it works, sometime it doesn't. How should I proceed?
