### ISSUE TITLE
Add "check by overlap" process in the backgrounddColor processing

### ISSUE THREAD

**Issue by WixeI** [Flutter-Vision/FluterVision#231]
Make the processing of background from children being passed to parent better. 

Instead of just being passed from the last child, the condition is: the child that ocupies the biggest area of the parent AND has this area be at least 90% of the parent is the one who will pass its backgroundColor for the parent. If no child completes these requisites, the parent will retain its backgroundColor.

**Comment by WixeI** [comment]
**How to Test:**
Have a component that has at least one child. Change the component type to "button", for example. The backgroundColor should remain the same **unless** one child occupies at least 90% of this component's area, then its background color should be passed to the parent.

**Comment by kaiquemancoso** [comment]
I'm still having problems when changing the component type. Sometimes it works, sometime it doesn't. How should I proceed?

**Comment by kaiquemancoso** [comment]
I tested a blue component with more than 90% of its parent (which had purple background), so when I changed the parent's type, the new background color was grey.

**Comment by kaiquemancoso** [comment]
Still not working

**Comment by ZoiParaschou** [comment]
The issue is duplicated to gitlab
