### ISSUE TITLE
#233 Add VerticalResizing & HorizontalResizing to the list of exceptions when passing properties from children to parent

### ISSUE THREAD

**Issue by WixeI** [Flutter-Vision/FluterVision#232]
This means the children will not pass these properties to the parent anymore when changing type of parent. They doing this is a bug.

**Comment by WixeI** [comment]
**How to Test:**
Check if the child of a component and the component itself has verticalSizing and horizontalSizing. Make sure they have different values. Then, change the type of the component (the parent) to anything (a button, for example). The verticalSizing and horizontalSizing of the parent should remain the same. If it changes to be equal to any of its children, the implementation failed.

**Comment by kaiquemancoso** [comment]
I can't change the type of components, so I didn't finish the test.

**Comment by kaiquemancoso** [comment]
I opened the issue #244

**Comment by kaiquemancoso** [comment]
I'm still having problems when changing the component type. Sometimes it works, sometime it doesn't. How should I proceed?
