### ISSUE TITLE
Retain VerticalResizing and HorizontalResizing properties of a component when changing types

### ISSUE THREAD

**Issue by WixeI** [Flutter-Vision/FluterVision#233]
If you change the type of any component that has VerticalResizing and HorizontalResizing properties, they should be the same after the type change. They not being is a bug (it's cleaning the fields of these properties).

**Comment by kaiquemancoso** [comment]
There is a bug when changing the type. So I have to wait this one to be solved. Then I will test it.

**Comment by kaiquemancoso** [comment]
I opened the issue #244

**Comment by kaiquemancoso** [comment]
I'm still having problems when changing the component type. Sometimes it works, sometime it doesn't. How should I proceed?
