### ISSUE TITLE
A new component does not appear on export

### ISSUE THREAD

**Issue by ZoiParaschou** [Flutter-Vision/FluterVision#234]
I added a new component and I declared it as a button. After export,  this button does not appear

**Comment by ZoiParaschou** [comment]
Figma file:
https://www.figma.com/file/tc9P25sWAKdQS6ubpjr1Z9/IoT-(ORIGINAL)-(Copy)?node-id=0%3A1

Flutter import 
![image](https://user-images.githubusercontent.com/91560490/168970899-c5cc59c0-cab8-440d-a2f9-0d77e2f3be1d.png)

Flutter export (appears only the first button)
![image](https://user-images.githubusercontent.com/91560490/168971033-83afcb0b-5c5f-4733-a65f-ac5798d8eeb4.png)

**Comment by ricardobna** [comment]
The components are appearing but its position is not matching the what's shown on the front end.
