### ISSUE TITLE
When an image change to button, text does not appear on export

### ISSUE THREAD

**Issue by ZoiParaschou** [Flutter-Vision/FluterVision#235]

**Comment by ZoiParaschou** [comment]
Figma file: https://www.figma.com/file/tc9P25sWAKdQS6ubpjr1Z9/IoT-(ORIGINAL)-(Copy)?node-id=0%3A1
Flutter import :
![image](https://user-images.githubusercontent.com/91560490/168974784-c0844727-6f8b-464c-bd9f-a8d3632770a9.png)
Flutter export: 
![image](https://user-images.githubusercontent.com/91560490/168974894-68ee9092-2446-4b10-9cb4-ab1f4d0f8c06.png)

**Comment by ricardobna** [comment]
Mentioned [here](https://github.com/Flutter-Vision/FlutterVision/issues/234), it is being exported, just not matching the front end to the exported files.

**Comment by ZoiParaschou** [comment]
Needs a label because is recognized as an image. Maybe we could appear a warning message?

**Comment by ZoiParaschou** [comment]
Even when I add a text field in my figma file (https://www.figma.com/file/ihaClxVQPSvePyPkB3hHY0/Test?node-id=1%3A8) ,
the text does not appear on export
import:
![image](https://user-images.githubusercontent.com/91560490/170468743-e6a5b36a-f3f4-423b-b958-cac81cad95a5.png)
export:
![image](https://user-images.githubusercontent.com/91560490/170468700-0c8fe765-04ec-46c8-a907-a42c6de09a6b.png)

**Comment by ZoiParaschou** [comment]
Now the text appears but appears also the text from Button. When the Button does not have a label, then no text should be on the Button.
![image](https://user-images.githubusercontent.com/91560490/170518273-f3bb292a-db5e-48bb-b273-0943238c4fc2.png)

**Comment by ricardobna** [comment]
Fixed the issue about using the name of the component when no label is provided on branch fix/#235.

**Comment by ZoiParaschou** [comment]
I tested but the label still appears.

**Comment by ZoiParaschou** [comment]
The issue is fixed
![image](https://user-images.githubusercontent.com/91560490/171610415-fdb554d2-7737-4ea5-99b5-ccbc6810bc91.png)
