### ISSUE TITLE
#158 When you group a container in frontend, understand automatically if it should be vertical or in horizontal direction

### ISSUE THREAD

**Issue by rene-kt** [Flutter-Vision/FluterVision#248]
How to test it: 
- Create a container in frontend with the Group Elements feature
- If the container should be vertical, so it will put vertical automatically, otherwise it will put as horizontal 

> The decision is made based on the position of the components, if the components are side by side, it should be horizontal. If they're one above the other, should be vertical

**Comment by kaiquemancoso** [comment]
How this decision is made? No description provided.

**Comment by rene-kt** [comment]
> How to test it:
> 
>     * Create a container in frontend with the Group Elements feature
> 
>     * If the container should be vertical, so it will put vertical automatically, otherwise it will put as horizontal

@kaiquemancoso
