### ISSUE TITLE
When moving a screen it's changing from a screen to another

### ISSUE THREAD

**Issue by kaiquemancoso** [Flutter-Vision/FluterVision#258]
If I select the screen 5 and try to move it (Move screen tool), it's changing the view from the screen 5 to the screen 2.
Sample: https://www.figma.com/file/hhIGxM7o6Svm9o0rnV5SKz/KnowCommerce?node-id=115%3A3103

**Comment by ricardobna** [comment]
Had this issue without being on the move screen tool, although I did click on the move screen button as my first action on the webpage. Opening it again it still keeps happening so I'm not sure if it is related to the move screen tool.
