### ISSUE TITLE
Bug transparent color

### ISSUE THREAD

**Issue by mateuslimax22** [Flutter-Vision/FluterVision#259]
the user cannot drag the transparency bar

Test : Drag the transparency bar

![Screenshot from 2022-05-11 15-33-23](https://user-images.githubusercontent.com/38704964/170315295-3c6fcbf9-a9b0-4ff5-9ddd-3f20ececfab3.png)
.

**Comment by ZoiParaschou** [comment]
Is not transparent, has a selected background color (black). @mateuslimax22 if I understand correctly, we could close this issue.

**Comment by kaiquemancoso** [comment]
It seems it's not working. I'm clicking on the bar and dragging it, but it's moving just a small part. Is it correct?

**Comment by kaiquemancoso** [comment]
@ZoiParaschou @dkatsianos maybe we should check and then add this issue on Gitlab.

**Comment by kaiquemancoso** [comment]
It's not working on the screen page, but it's working on properties
