### ISSUE TITLE
#233 Changing screen to Flex is giving invalid application

### ISSUE THREAD

**Issue by WixeI** [Flutter-Vision/FluterVision#260]
Changing screen layout to stack and saving returns invalid application. Any screen. If it's already a stack, it saves fine.

**How to Test:** Get a **screen** that is in absolute or relative, change it to stack, then save. If is does not throw any errors (error modal), it's working.

PS: since the names may have the flutter pattern, what I mean by stack is the auto-layout from figma. I believe it's called flex in flutter, but I'm not sure.

**Comment by kaiquemancoso** [comment]
I tested with this sample: [https://www.figma.com/file/hhIGxM7o6Svm9o0rnV5SKz/KnowCommerce?node-id=115%3A3107](https://www.figma.com/file/hhIGxM7o6Svm9o0rnV5SKz/KnowCommerce?node-id=115%3A3107)

I changed the screens 1, 2 and 3 to stack, then clicked on Save and I got this: ERROR: Invalid application Εrror ID:911

**Comment by kaiquemancoso** [comment]
It's still not working
