### ISSUE TITLE
Lost specific information

### ISSUE THREAD

**Issue by mateuslimax22** [Flutter-Vision/FluterVision#263]
when I change the container type to button the specific information is lost.
![Screenshot from 2022-05-25 11-55-21](https://user-images.githubusercontent.com/38704964/170325366-474c926f-d634-4562-9496-8943ebeefd59.png)

**Comment by ZoiParaschou** [comment]
This happens only to backtest and not on production. Also, this happens to all kinds of types(not only button). 
If the container exists, the first time works but then can not be changed again. 
If the container is new can not be changed even the first time.

**Comment by ZoiParaschou** [comment]
This issue is fixed
