### ISSUE TITLE
Export not getting the right color for buttons (sometimes)

### ISSUE THREAD

**Issue by brunoamuniz** [Flutter-Vision/FluterVision#71]
## **Describe the bug**
Export is not getting the right color for buttons at some prototypes

https://www.figma.com/file/Ha3MOi5izznE67Kr0ZRSya/To-The-Plane-app-(Community)?node-id=491%3A2795

<img width="1055" alt="Screen Shot 2022-03-29 at 13 05 46" src="https://user-images.githubusercontent.com/3296036/160656431-4c415157-4359-42b6-b8ff-5409bca1ff99.png">

**Comment by dkatsianos** [comment]
@Bruno I did a lot of tests and I could not reproduce this bug.

**Comment by pattrickx** [comment]
I did some tests here, can't replicate the error @dkatsianos @ZoiParaschou @kaiquemancoso
