### ISSUE TITLE
Container on top of image is not working

### ISSUE THREAD

**Issue by brunoamuniz** [Flutter-Vision/FluterVision#73]
## **Describe the bug**

If we have a container on top of a image, FlutterVision is exporting image and then container, like the image below.

Using Constraint Layout

https://www.figma.com/file/Ha3MOi5izznE67Kr0ZRSya/To-The-Plane-app-(Community)?node-id=660%3A3311

<img width="885" alt="Screen Shot 2022-03-29 at 16 54 54" src="https://user-images.githubusercontent.com/3296036/160696239-ec229156-83e9-45e8-b162-0ad15760fd69.png">

**Comment by teras** [comment]
What is the default layout of the root container?
Is there any z-ordering?

**Comment by brunoamuniz** [comment]
> What is the default layout of the root container? Is there any z-ordering?

all details are in the Figma file informed =)

**Comment by teras** [comment]
> > What is the default layout of the root container? Is there any z-ordering?
> 
> all details are in the Figma above =)

It's not clear on Figma's interface. I tried it :) 
That's why I put the comments here, to have them as reference.

Maybe this task should start with @pattrickx

**Comment by brunoamuniz** [comment]
Ok,

so the main UI is using constraint layout. we have on container using auto layout for the image and another container (outside the first one), on top of it, using auto layout too.

<img width="131" alt="Screen Shot 2022-03-30 at 09 04 12" src="https://user-images.githubusercontent.com/3296036/160830615-fd9f0be4-59a4-45ca-b013-5ec45b04fdfa.png">

**Comment by pattrickx** [comment]
I took a look at this problem, what is happening is that the AI ​​is identifying the container that is above the image as part of the image, in this way it is making everything inside this container an image. This cannot be fixed in code, it can be improved by retraining the AI ​​or changing the design so that the AI ​​detects differently.

**Comment by pattrickx** [comment]
these issues will be resolved by issue #87
