### ISSUE TITLE
Support Properties from Figma on Front-end

### ISSUE THREAD

**Issue by kaiquemancoso** [Flutter-Vision/FluterVision#74]
These properties should appear also on Front-end, but respecting the FLUTTER properties names.

https://docs.google.com/spreadsheets/d/1-yne5AouzBUhg_Ak-K-WZulfpKs2xe0-JJNBWU8cUqA/edit?usp=sharing

**Comment by mateuslimax22** [comment]
Auto Layout

	Alignment Packed
	Resizing : Fill Containers

Constraints
	
	Horizontal: Fixed - Center
	Horizontal: Fixed - Scale
	Horizontal: Hug Contents - Left
	Horizontal: Hug Contents - Right
	Horizontal: Hug Contents - Center
	Vertical: Hug Contents - Top
	Vertical: Hug Contents - Bottom
	Vertical: Hug Contents - Center
