### ISSUE TITLE
AI Refactoring

### ISSUE THREAD

**Issue by ZoiParaschou** [Flutter-Vision/FluterVision#87]
Improve AI to better support the new components and have a better dataset.

**Comment by pattrickx** [comment]
Simplified step-by-step to update our AI model

- [ ] Define which components should be added to the initial set.
- [ ] Define what each component is, shapes and what is contained by each, with example images.
- [ ] Add new screenshots to the existing dataset.
- [ ] Update image tagging code with the new information.
- [ ] Separate data to be marked by our developers, or seek people willing to receive to do this work.
- [ ] Pass the information on how the markings should be made and do a supervised test, with data that were previously marked, within the defined pattern.
- [ ] Send data packet to markers.
- [ ] Check and correct incorrect tags, and assign tags to future packages.
- [ ] Start training and testing with new dataset.
- [ ] Check the quality of the result of the new models.
- [ ] Replace current production model
