### ISSUE TITLE
Create new components

### ISSUE THREAD

**Issue by teras** [Flutter-Vision/FluterVision#89]
We have a list of these components that should be supported.
Revise which components are still missing and what needs to be done.

- [x] Row
- [x] Column
- [ ] Card
- [x] Stack
- [ ] ListView
- [x] Text
- [x] Button (Text, Elevated and Outlined)
- [x] TextFormField
- [ ] AppBar
- [ ] BottomBar
- [ ] Tab
- [x] Image
- [x] DropDown
- [ ] SearchView
- [x] Slider

**Comment by kaiquemancoso** [comment]
https://docs.google.com/spreadsheets/d/1Vr-cLouBbkP8onyQizjxC4j8B3wlNisbQoeCcDlvkLE/edit?usp=sharing

**Comment by pedrohcbrl** [comment]
This issue will be divided in more specific issues, each one assigned to an application area (backend, frontend or AI).
