### ISSUE TITLE
When the user logs in, the page should translate to his language field

### ISSUE THREAD

**Issue by mateuslimax22** [Flutter-Vision/FluterVision#95]
![image](https://user-images.githubusercontent.com/38704964/162025870-bc6991a6-63a2-45a0-ab05-c69c46abc631.png)

On this route

**Comment by brunoamuniz** [comment]
expected behavior:  if you change for portuguese, and then leave It, the info should be saved and the flutter vision should be in portuguese

**Comment by brunoamuniz** [comment]
@mateuslimax22 I changed the language but when I came back FV didnt get the right language of the web application... it keeps in english

<img width="719" alt="Screen Shot 2022-04-15 at 16 07 28" src="https://user-images.githubusercontent.com/3296036/163622134-6e201713-8ab7-415f-8cf5-62e8e51421d1.png">
